### ISSUE TITLE
VMFS detection errors ungracefully on too small volumes

### ISSUE THREAD

**Issue by JSCU-CNI** [fox-it/dissect.target#167]
The detection of vmfs lvm volumes seems to be broken on both `dissect.vmfs-3.3.dev2` and `dissect.vmfs-3.2`.

```
$ target-shell ./example.vmdk
2023-02-09T14:27:44.232895Z [warning  ] Failed to detect VMFS LVM [dissect.target.volumes.vmfs] 
Traceback (most recent call last):
  File ".../dissect.target/dissect/target/volumes/vmfs.py", line 50, in detect_volume
    return struct.unpack("<I", buf[:4])[0] == c_vmfs.VMFS_LVM_DEVICE_META_MAGIC
struct.error: unpack requires a buffer of 4 bytes

...

2023-02-09T14:27:44.284509Z [warning  ] Failed to detect VMFS filesystem [dissect.target.filesystems.vmfs] 
Traceback (most recent call last):
  File ".../dissect.target/dissect/target/filesystems/vmfs.py", line 34, in detect
    return struct.unpack("<I", sector[:4])[0] in (
struct.error: unpack requires a buffer of 4 bytes
```

**Comment by Schamper** [comment]
This error seems to happen because the read operation just above that check (`buf = fh.read(512)`) returns 0 bytes, which could be because for some reason your VMFS volume starts at a different offset (currently only one offset is checked at `VMFS_LVM_DEVICE_META_BASE`, which is `0x00100000`), or reading from the partition/VMDK is borked for some reason.

From reverse engineering I've seen that LVM can technically start at different offsets, but those are all larger than `0x00100000`, so that wouldn't explain this behaviour.

Is `example.vmdk` reproducible test data? If so, can you either share it or share instructions on how to reproduce? I was just using VMFS this morning and that worked fine on my own virtual machines.

**Comment by JSCU-CNI** [comment]
Thanks. This behaviour occurs on a clean installation of a Proxmox 7.3 VE system (https://www.proxmox.com/en/downloads/item/proxmox-ve-7-3-iso-installer). The installer will create three volumes by default:

```
- <Volume name='part_00004400' size=1030656 fs=None>
- <Volume name='part_00100000' size=536870400 fs=<FatFilesystem>>
- <Volume name='part_20100000' size=42411736064 fs=None>
```

**Comment by Schamper** [comment]
Proxmox uses VMFS itself? Or are you trying to access the disk of a virtual machine within Proxmox?

I'm aware of issues with the way Proxmox uses LVM2 (not VMFS LVM), because it basically uses Linux software RAID which we don't currently implement.

**Comment by JSCU-CNI** [comment]
Yes Proxmox uses LVM by default (https://pve.proxmox.com/wiki/Logical_Volume_Manager_(LVM)).

**Comment by Schamper** [comment]
Yes I know, so it seems in this case the VMFS volume detection tried to detect something at offset 0x100000 while the first volume is only of size 0xfba00. We can improve the error checking here to make sure this error doesn't incorrectly show up in situations like this.
